CM.make("$/basis.cm");
CM.make("$/ml-yacc-lib.cm");
use "while-ast.sml";
use "while.yacc.sig";
use "while.yacc.sml";
use "while.lex.sml";
use "typeChecker.sml";
use "stack.sml";
use "funstack.sml";
use "Vmc.sml";
use "load-while.sml";
Control.Print.printLength := 1000;
Control.Print.printDepth := 1000;
Control.Print.stringDepth := 1000;